#!/bin/bash
count1=0
for word in $(cat "$2"); do
  if [ $word == "$1" ]; then
    count1=$((count1 + 1))
  fi
done
count2=0
for word in $(cat "$3"); do
  if [ $word == "$1" ]; then
    count2=$((count2 + 1))
  fi
done
if [ $count2 -gt $count1 ]; then
  echo "$3"
elif [ $count1 -gt $count2 ]; then
  echo "$2"
else
  echo "$2 $3"
fi
